argocd:
  giropopsSenhas:
    enabled: true
    replicas: 3
  randomLogger:
    enabled: true
  prometheus:
    enabled: false
    ingress: "https://prometheus-mycompany.com"
  grafana:
    enabled: false
    ingress: "https://grafana-mycompany.com"