apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https:/grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: 7.0.19
      helm:
        valuesFiles:
        - $repo/grafana/values.yaml
    - repoURL: 'https://github.com/GustafFig/descomplicando-gitops-no-kubernetes-argocd'
      targetRevision: feat/day2
      ref: repo
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
